addons:
  postgresql: 9.6
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
dist: trusty
env:
  - CC_TEST_REPORTER_ID=45cb98949c9d746bd8179c22677112ce905e5a2a6dd6f00f1e8e86a1932244df
  - HOST_API=http://localhost:3000
language: ruby
rvm:
  - 2.4.3
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
